### ISSUE TITLE
大佬，拉取了你的脚本，有COOKIE输入框了

### ISSUE THREAD

**Issue by ssthptfpd** [Waikkii/Waikiki_ninja#1]
但是填入PT_key显示获取用户信息失败，请不吝赐教呀，谢谢。

**Comment by Waikkii** [comment]
> 但是填入PT_key显示获取用户信息失败，请不吝赐教呀，谢谢。

获取用户信息失败可能是京东接口的问题，有人反馈概率成功，很抱歉我没有解决办法。
另外，指路原作者：https://github.com/MoonBegonia/ninja
