### ISSUE TITLE
我重新拉ninja之后，显示这个应该是正常的，但是ninja文件夹里还是空的

### ISSUE THREAD

**Issue by xuexinxiansheng** [Waikkii/Waikiki_ninja#11]
![image](https://user-images.githubusercontent.com/63955913/132982196-315f20e2-f84d-488e-ad3e-a02173deaeb8.png)
![image](https://user-images.githubusercontent.com/63955913/132982216-f482f9ff-9f2f-467f-a33a-fdca09e1b8ae.png)

**Comment by Waikkii** [comment]
先好好百度一下docker的映射吧大哥，容器外ql1对应你容器里的ql，那你在容器内ql1clone有啥用呢
