### ISSUE TITLE
刚刚更新完，登录后不能修改备注

### ISSUE THREAD

**Issue by mjyhj** [Waikkii/Waikiki_ninja#12]
目前不能修改备注，WSKEY也不能录入

另外希望可以自动选择开关WSKEY录入，还有可以显示推送的二维码图片

**Comment by Waikkii** [comment]
> 目前不能修改备注。
> 
> 
> 
> 
> 
> 另外希望可以自动选择开关WSKEY录入，还有可以显示推送的二维码图片

刚更新的最后一版可以实现ck和wsck同时备注
主页的wsck开关可以.env里控制
个人中心里的暂时不考虑去掉
二维码过几天看看 应该不难

**Comment by Waikkii** [comment]
> 目前不能修改备注，WSKEY也不能录入
> 
> 另外希望可以自动选择开关WSKEY录入，还有可以显示推送的二维码图片

![image](https://user-images.githubusercontent.com/50266226/132987227-04e23d09-f083-4abf-84cb-0be72b06bba3.png)

**Comment by w900316** [comment]
> > 目前不能修改备注，WSKEY也不能录入
> > 另外希望可以自动选择开关WSKEY录入，还有可以显示推送的二维码图片
> 
> ![image](https://user-images.githubusercontent.com/50266226/132987227-04e23d09-f083-4abf-84cb-0be72b06bba3.png)

.env里已开，但是wsck录入没任何反应啊
