### ISSUE TITLE
打开首页ck登录报错无响应

### ISSUE THREAD

**Issue by AndyNull** [Waikkii/Waikiki_ninja#14]
控制台输出
从打开首页开始报错：index.34a494f0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showQR')
    at t (index.34a494f0.js:1)
    at index.34a494f0.js:1
    at di (vendor.4eb73c88.js:1)
    at pi (vendor.4eb73c88.js:1)
    at Array.t.__weh.t.__weh (vendor.4eb73c88.js:1)
    at Fi (vendor.4eb73c88.js:1)
    at Bi (vendor.4eb73c88.js:1)
t @ index.34a494f0.js:1
(anonymous) @ index.34a494f0.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
t.__weh.t.__weh @ vendor.4eb73c88.js:1
Fi @ vendor.4eb73c88.js:1
Bi @ vendor.4eb73c88.js:1
Promise.then (async)
ji @ vendor.4eb73c88.js:1
Pi @ vendor.4eb73c88.js:1
Mi @ vendor.4eb73c88.js:1
Pn @ vendor.4eb73c88.js:1
(anonymous) @ vendor.4eb73c88.js:1
Ye @ vendor.4eb73c88.js:1
Kt @ vendor.4eb73c88.js:1
(anonymous) @ vendor.4eb73c88.js:1
Ye @ vendor.4eb73c88.js:1
Kt @ vendor.4eb73c88.js:1
(anonymous) @ vendor.4eb73c88.js:1
Ye @ vendor.4eb73c88.js:1
Kt @ vendor.4eb73c88.js:1
set value @ vendor.4eb73c88.js:1
x @ vendor.4eb73c88.js:21
(anonymous) @ vendor.4eb73c88.js:21
Promise.then (async)
y @ vendor.4eb73c88.js:21
v @ vendor.4eb73c88.js:21
install @ vendor.4eb73c88.js:21
use @ vendor.4eb73c88.js:1
(anonymous) @ index.34a494f0.js:1
点击ck登录无响应，并报错下面这个，
index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'eid')
    at CKLogin (index.34a494f0.js:1)

**Comment by Waikkii** [comment]
> 控制台输出
> 从打开首页开始报错：index.34a494f0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showQR')
> at t (index.34a494f0.js:1)
> at index.34a494f0.js:1
> at di (vendor.4eb73c88.js:1)
> at pi (vendor.4eb73c88.js:1)
> at Array.t.__weh.t.__weh (vendor.4eb73c88.js:1)
> at Fi (vendor.4eb73c88.js:1)
> at Bi (vendor.4eb73c88.js:1)
> t @ index.34a494f0.js:1
> (anonymous) @ index.34a494f0.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> t.__weh.t.__weh @ vendor.4eb73c88.js:1
> Fi @ vendor.4eb73c88.js:1
> Bi @ vendor.4eb73c88.js:1
> Promise.then (async)
> ji @ vendor.4eb73c88.js:1
> Pi @ vendor.4eb73c88.js:1
> Mi @ vendor.4eb73c88.js:1
> Pn @ vendor.4eb73c88.js:1
> (anonymous) @ vendor.4eb73c88.js:1
> Ye @ vendor.4eb73c88.js:1
> Kt @ vendor.4eb73c88.js:1
> (anonymous) @ vendor.4eb73c88.js:1
> Ye @ vendor.4eb73c88.js:1
> Kt @ vendor.4eb73c88.js:1
> (anonymous) @ vendor.4eb73c88.js:1
> Ye @ vendor.4eb73c88.js:1
> Kt @ vendor.4eb73c88.js:1
> set value @ vendor.4eb73c88.js:1
> x @ vendor.4eb73c88.js:21
> (anonymous) @ vendor.4eb73c88.js:21
> Promise.then (async)
> y @ vendor.4eb73c88.js:21
> v @ vendor.4eb73c88.js:21
> install @ vendor.4eb73c88.js:21
> use @ vendor.4eb73c88.js:1
> (anonymous) @ index.34a494f0.js:1
> 点击ck登录无响应，并报错下面这个，
> index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'eid')
> at CKLogin (index.34a494f0.js:1)

今天白天测试时的bug
请git pull
最新版本没问题

**Comment by AndyNull** [comment]
> > 控制台输出
> > 从打开首页开始报错：index.34a494f0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showQR')
> > at t (index.34a494f0.js:1)
> > at index.34a494f0.js:1
> > at di (vendor.4eb73c88.js:1)
> > at pi (vendor.4eb73c88.js:1)
> > at Array.t.__weh.t.__weh (vendor.4eb73c88.js:1)
> > at Fi (vendor.4eb73c88.js:1)
> > at Bi (vendor.4eb73c88.js:1)
> > t @ index.34a494f0.js:1
> > (anonymous) @ index.34a494f0.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > t.__weh.t.__weh @ vendor.4eb73c88.js:1
> > Fi @ vendor.4eb73c88.js:1
> > Bi @ vendor.4eb73c88.js:1
> > Promise.then (async)
> > ji @ vendor.4eb73c88.js:1
> > Pi @ vendor.4eb73c88.js:1
> > Mi @ vendor.4eb73c88.js:1
> > Pn @ vendor.4eb73c88.js:1
> > (anonymous) @ vendor.4eb73c88.js:1
> > Ye @ vendor.4eb73c88.js:1
> > Kt @ vendor.4eb73c88.js:1
> > (anonymous) @ vendor.4eb73c88.js:1
> > Ye @ vendor.4eb73c88.js:1
> > Kt @ vendor.4eb73c88.js:1
> > (anonymous) @ vendor.4eb73c88.js:1
> > Ye @ vendor.4eb73c88.js:1
> > Kt @ vendor.4eb73c88.js:1
> > set value @ vendor.4eb73c88.js:1
> > x @ vendor.4eb73c88.js:21
> > (anonymous) @ vendor.4eb73c88.js:21
> > Promise.then (async)
> > y @ vendor.4eb73c88.js:21
> > v @ vendor.4eb73c88.js:21
> > install @ vendor.4eb73c88.js:21
> > use @ vendor.4eb73c88.js:1
> > (anonymous) @ index.34a494f0.js:1
> > 点击ck登录无响应，并报错下面这个，
> > index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'eid')
> > at CKLogin (index.34a494f0.js:1)
> 
> 今天白天测试时的bug
> 请git pull
> 最新版本没问题

非常感谢这么晚还在，刚拉了确实没问题，只是这个首页报错的怎么解决啊，明天再看吧，都先休息了

**Comment by Waikkii** [comment]
> > > 控制台输出
> 
> > > 从打开首页开始报错：index.34a494f0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showQR')
> 
> > > at t (index.34a494f0.js:1)
> 
> > > at index.34a494f0.js:1
> 
> > > at di (vendor.4eb73c88.js:1)
> 
> > > at pi (vendor.4eb73c88.js:1)
> 
> > > at Array.t.__weh.t.__weh (vendor.4eb73c88.js:1)
> 
> > > at Fi (vendor.4eb73c88.js:1)
> 
> > > at Bi (vendor.4eb73c88.js:1)
> 
> > > t @ index.34a494f0.js:1
> 
> > > (anonymous) @ index.34a494f0.js:1
> 
> > > di @ vendor.4eb73c88.js:1
> 
> > > pi @ vendor.4eb73c88.js:1
> 
> > > t.__weh.t.__weh @ vendor.4eb73c88.js:1
> 
> > > Fi @ vendor.4eb73c88.js:1
> 
> > > Bi @ vendor.4eb73c88.js:1
> 
> > > Promise.then (async)
> 
> > > ji @ vendor.4eb73c88.js:1
> 
> > > Pi @ vendor.4eb73c88.js:1
> 
> > > Mi @ vendor.4eb73c88.js:1
> 
> > > Pn @ vendor.4eb73c88.js:1
> 
> > > (anonymous) @ vendor.4eb73c88.js:1
> 
> > > Ye @ vendor.4eb73c88.js:1
> 
> > > Kt @ vendor.4eb73c88.js:1
> 
> > > (anonymous) @ vendor.4eb73c88.js:1
> 
> > > Ye @ vendor.4eb73c88.js:1
> 
> > > Kt @ vendor.4eb73c88.js:1
> 
> > > (anonymous) @ vendor.4eb73c88.js:1
> 
> > > Ye @ vendor.4eb73c88.js:1
> 
> > > Kt @ vendor.4eb73c88.js:1
> 
> > > set value @ vendor.4eb73c88.js:1
> 
> > > x @ vendor.4eb73c88.js:21
> 
> > > (anonymous) @ vendor.4eb73c88.js:21
> 
> > > Promise.then (async)
> 
> > > y @ vendor.4eb73c88.js:21
> 
> > > v @ vendor.4eb73c88.js:21
> 
> > > install @ vendor.4eb73c88.js:21
> 
> > > use @ vendor.4eb73c88.js:1
> 
> > > (anonymous) @ index.34a494f0.js:1
> 
> > > 点击ck登录无响应，并报错下面这个，
> 
> > > index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'eid')
> 
> > > at CKLogin (index.34a494f0.js:1)
> 
> > 
> 
> > 今天白天测试时的bug
> 
> > 请git pull
> 
> > 最新版本没问题
> 
> 
> 
> 非常感谢这么晚还在，刚拉了确实没问题，只是这个首页报错的怎么解决啊，明天再看吧，都先休息了

应该是.env没读到 showQR 你把showQR注释去了改成false估计可以了。不影响功能我就不改了

**Comment by AndyNull** [comment]
> > > > 控制台输出
> > 
> > 
> > > > 从打开首页开始报错：index.34a494f0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showQR')
> > 
> > 
> > > > at t (index.34a494f0.js:1)
> > 
> > 
> > > > at index.34a494f0.js:1
> > 
> > 
> > > > at di (vendor.4eb73c88.js:1)
> > 
> > 
> > > > at pi (vendor.4eb73c88.js:1)
> > 
> > 
> > > > at Array.t.__weh.t.__weh (vendor.4eb73c88.js:1)
> > 
> > 
> > > > at Fi (vendor.4eb73c88.js:1)
> > 
> > 
> > > > at Bi (vendor.4eb73c88.js:1)
> > 
> > 
> > > > t @ index.34a494f0.js:1
> > 
> > 
> > > > (anonymous) @ index.34a494f0.js:1
> > 
> > 
> > > > di @ vendor.4eb73c88.js:1
> > 
> > 
> > > > pi @ vendor.4eb73c88.js:1
> > 
> > 
> > > > t.__weh.t.__weh @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Fi @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Bi @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Promise.then (async)
> > 
> > 
> > > > ji @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Pi @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Mi @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Pn @ vendor.4eb73c88.js:1
> > 
> > 
> > > > (anonymous) @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Ye @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Kt @ vendor.4eb73c88.js:1
> > 
> > 
> > > > (anonymous) @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Ye @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Kt @ vendor.4eb73c88.js:1
> > 
> > 
> > > > (anonymous) @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Ye @ vendor.4eb73c88.js:1
> > 
> > 
> > > > Kt @ vendor.4eb73c88.js:1
> > 
> > 
> > > > set value @ vendor.4eb73c88.js:1
> > 
> > 
> > > > x @ vendor.4eb73c88.js:21
> > 
> > 
> > > > (anonymous) @ vendor.4eb73c88.js:21
> > 
> > 
> > > > Promise.then (async)
> > 
> > 
> > > > y @ vendor.4eb73c88.js:21
> > 
> > 
> > > > v @ vendor.4eb73c88.js:21
> > 
> > 
> > > > install @ vendor.4eb73c88.js:21
> > 
> > 
> > > > use @ vendor.4eb73c88.js:1
> > 
> > 
> > > > (anonymous) @ index.34a494f0.js:1
> > 
> > 
> > > > 点击ck登录无响应，并报错下面这个，
> > 
> > 
> > > > index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'eid')
> > 
> > 
> > > > at CKLogin (index.34a494f0.js:1)
> > 
> > 
> > > 
> > 
> > 
> > > 今天白天测试时的bug
> > 
> > 
> > > 请git pull
> > 
> > 
> > > 最新版本没问题
> > 
> > 
> > 非常感谢这么晚还在，刚拉了确实没问题，只是这个首页报错的怎么解决啊，明天再看吧，都先休息了
> 
> 应该是.env没读到 showQR 你把showQR注释去了改成false估计可以了。不影响功能我就不改了

还没有测试这个，主要是有时候改env文件，重新pm2 start也不一定会生效，很迷。
刚刚多开个一个ninja  发现无法打开，就算是改了端口和放行
