### ISSUE TITLE
访问ninja时, 登录ck部分闪一下就消失了, 是什么原因

### ISSUE THREAD

**Issue by AlterGu** [Waikkii/Waikiki_ninja#15]

**Comment by Waikkii** [comment]
看看f12控制台有什么报错

**Comment by LuomingXu** [comment]
与 #14 一样的错误

![image](https://user-images.githubusercontent.com/24503603/133018980-4290323f-0186-4773-988e-d6a1fb407a1b.png)

添加了环境变量, pm2 start了, 也还是这个问题, 一闪而过
![image](https://user-images.githubusercontent.com/24503603/133019063-4384b485-1ac5-48b0-ab16-f1b04a56a14e.png)

**Comment by Waikkii** [comment]
emmmm变量在.env里，你把showQR那一行的注释去了，改成false就好了

**Comment by LuomingXu** [comment]
我是再容器内, 和qinglong一个容器, 直接执行的
```sh
git clone https://github.com/Waikkii/waikiki_ninja.git /ql/ninja
cd /ql/ninja/backend
pnpm install
pm2 start
# cp sendNotify.js /ql/scripts/sendNotify.js 这个没有执行, 本来就有
```
和extra.sh

没有找到.env, 只有.env.example

**Comment by Waikkii** [comment]
仔细看readme cp一份example为env 自己改变量

**Comment by LuomingXu** [comment]
![image](https://user-images.githubusercontent.com/24503603/133019704-f60c71fb-4d50-4e75-8dea-23f34e5a0c43.png)

因为它是包含在"容器外"章节里面的, 所以没有执行
这个也要改?

**Comment by LuomingXu** [comment]
Okay了, 感觉你需要在容器内章节也加上这个...
```sh
cp .env.example .env # 如有需要, 修改.env
```

**Comment by Waikkii** [comment]
> Okay了, 感觉你需要在容器内章节也加上这个...
> 
> ```shell
> cp .env.example .env # 如有需要, 修改.env
> ```

建议不错

**Comment by AlterGu** [comment]
可以了, 谢谢解答
