### ISSUE TITLE
wsck录入好像无效啊

### ISSUE THREAD

**Issue by w900316** [Waikkii/Waikiki_ninja#16]
env环境已改true
wsck录入好像无效啊，输入了一点反应都没有~

**Comment by Waikkii** [comment]
> env环境已改true
> 
> wsck录入好像无效啊，输入了一点反应都没有~

主页录入wsck没在测试机上验证哦，我记得没bug，个人中心页wsck是可以录入的没问题。

**Comment by w900316** [comment]
> > env环境已改true
> > wsck录入好像无效啊，输入了一点反应都没有~
> 
> 主页录入wsck没在测试机上验证哦，我记得没bug，个人中心页wsck是可以录入的没问题。

ck登录后的个人中心wsck录入也没反应啊，不知道是什么原因~能再次验证一下~

**Comment by Waikkii** [comment]
> > > env环境已改true
> 
> > > wsck录入好像无效啊，输入了一点反应都没有~
> 
> > 
> 
> > 主页录入wsck没在测试机上验证哦，我记得没bug，个人中心页wsck是可以录入的没问题。
> 
> 
> 
> ck登录后的个人中心wsck录入也没反应啊，不知道是什么原因~能再次验证一下~

没问题，自查是否最新版本，若还有问题f12控制台看network有无异常
![image](https://user-images.githubusercontent.com/50266226/133056569-135aea4d-7f17-48fc-a0e8-e9e847035516.jpeg)
![image](https://user-images.githubusercontent.com/50266226/133056603-20b1a69c-a479-4248-b219-047b99fae7ad.jpeg)
