### ISSUE TITLE
WSCK录入无效，控制台消息如下~

### ISSUE THREAD

**Issue by w900316** [Waikkii/Waikiki_ninja#17]
![1111111111111111111111111111111111111](https://user-images.githubusercontent.com/57336092/133065869-fda5344a-1c65-40e3-b377-c1f143965047.png)

**Comment by Waikkii** [comment]
实测最新版 主页和个人中心页录入WSCK都没问题，只是主页录入暂时不能显示nickname
![image](https://user-images.githubusercontent.com/50266226/133076029-1cc0f63e-512e-45cb-9502-1bafe5e3b143.png)
