### ISSUE TITLE
首页新添加ck出现无响应

### ISSUE THREAD

**Issue by AndyNull** [Waikkii/Waikiki_ninja#18]
抱歉白天没啥时间，只有晚上搞搞
今天试了下，容器内存在ck，然后登录是ok的
但是新ck的话，登录直接无响应
控制台直接报错如下，你看看：
POST http://xxxxx.cn/api/cklogin 500 (Internal Server Error)
(anonymous) @ vendor.4eb73c88.js:15
(anonymous) @ vendor.4eb73c88.js:15
_fetch @ vendor.4eb73c88.js:15
o @ vendor.4eb73c88.js:15
async function (async)
o @ vendor.4eb73c88.js:15
create @ vendor.4eb73c88.js:15
Qg.t.<computed> @ vendor.4eb73c88.js:16
(anonymous) @ index.34a494f0.js:1
CKLogin @ index.34a494f0.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
dn @ vendor.4eb73c88.js:1
handleClick @ vendor.4eb73c88.js:1
Vf.createBlock.onClick.t.<computed>.t.<computed> @ vendor.4eb73c88.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
n @ vendor.4eb73c88.js:1
vendor.4eb73c88.js:15 HTTPError: Request failed with status code 500 Internal Server Error
    at o (vendor.4eb73c88.js:15)
    at async Promise.r.<computed> [as json] (vendor.4eb73c88.js:15)
    at async CKLogin (index.34a494f0.js:1)
o @ vendor.4eb73c88.js:15
async function (async)
o @ vendor.4eb73c88.js:15
create @ vendor.4eb73c88.js:15
Qg.t.<computed> @ vendor.4eb73c88.js:16
(anonymous) @ index.34a494f0.js:1
CKLogin @ index.34a494f0.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
dn @ vendor.4eb73c88.js:1
handleClick @ vendor.4eb73c88.js:1
Vf.createBlock.onClick.t.<computed>.t.<computed> @ vendor.4eb73c88.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
n @ vendor.4eb73c88.js:1
vendor.4eb73c88.js:15 TypeError: Cannot read properties of undefined (reading 'clone')
    at Promise.r.<computed> [as json] (vendor.4eb73c88.js:15)
    at async CKLogin (index.34a494f0.js:1)
r.<computed> @ vendor.4eb73c88.js:15
async function (async)
r.<computed> @ vendor.4eb73c88.js:15
(anonymous) @ index.34a494f0.js:1
CKLogin @ index.34a494f0.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
dn @ vendor.4eb73c88.js:1
handleClick @ vendor.4eb73c88.js:1
Vf.createBlock.onClick.t.<computed>.t.<computed> @ vendor.4eb73c88.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
n @ vendor.4eb73c88.js:1
index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'data')
    at CKLogin (index.34a494f0.js:1)
CKLogin @ index.34a494f0.js:1
async function (async)
CKLogin @ index.34a494f0.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
dn @ vendor.4eb73c88.js:1
handleClick @ vendor.4eb73c88.js:1
Vf.createBlock.onClick.t.<computed>.t.<computed> @ vendor.4eb73c88.js:1
di @ vendor.4eb73c88.js:1
pi @ vendor.4eb73c88.js:1
n @ vendor.4eb73c88.js:1

**Comment by bugme2** [comment]
同，青龙最新版添加没反应

**Comment by Waikkii** [comment]
> 抱歉白天没啥时间，只有晚上搞搞
> 今天试了下，容器内存在ck，然后登录是ok的
> 但是新ck的话，登录直接无响应
> 控制台直接报错如下，你看看：
> POST http://xxxxx.cn/api/cklogin 500 (Internal Server Error)
> (anonymous) @ vendor.4eb73c88.js:15
> (anonymous) @ vendor.4eb73c88.js:15
> _fetch @ vendor.4eb73c88.js:15
> o @ vendor.4eb73c88.js:15
> async function (async)
> o @ vendor.4eb73c88.js:15
> create @ vendor.4eb73c88.js:15
> Qg.t. @ vendor.4eb73c88.js:16
> (anonymous) @ index.34a494f0.js:1
> CKLogin @ index.34a494f0.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> dn @ vendor.4eb73c88.js:1
> handleClick @ vendor.4eb73c88.js:1
> Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> n @ vendor.4eb73c88.js:1
> vendor.4eb73c88.js:15 HTTPError: Request failed with status code 500 Internal Server Error
> at o (vendor.4eb73c88.js:15)
> at async Promise.r. [as json] (vendor.4eb73c88.js:15)
> at async CKLogin (index.34a494f0.js:1)
> o @ vendor.4eb73c88.js:15
> async function (async)
> o @ vendor.4eb73c88.js:15
> create @ vendor.4eb73c88.js:15
> Qg.t. @ vendor.4eb73c88.js:16
> (anonymous) @ index.34a494f0.js:1
> CKLogin @ index.34a494f0.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> dn @ vendor.4eb73c88.js:1
> handleClick @ vendor.4eb73c88.js:1
> Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> n @ vendor.4eb73c88.js:1
> vendor.4eb73c88.js:15 TypeError: Cannot read properties of undefined (reading 'clone')
> at Promise.r. [as json] (vendor.4eb73c88.js:15)
> at async CKLogin (index.34a494f0.js:1)
> r. @ vendor.4eb73c88.js:15
> async function (async)
> r. @ vendor.4eb73c88.js:15
> (anonymous) @ index.34a494f0.js:1
> CKLogin @ index.34a494f0.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> dn @ vendor.4eb73c88.js:1
> handleClick @ vendor.4eb73c88.js:1
> Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> n @ vendor.4eb73c88.js:1
> index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'data')
> at CKLogin (index.34a494f0.js:1)
> CKLogin @ index.34a494f0.js:1
> async function (async)
> CKLogin @ index.34a494f0.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> dn @ vendor.4eb73c88.js:1
> handleClick @ vendor.4eb73c88.js:1
> Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> di @ vendor.4eb73c88.js:1
> pi @ vendor.4eb73c88.js:1
> n @ vendor.4eb73c88.js:1

是最新版的吗
无能为力了，主要四个测试鸡都正常，没遇到这个情况不知道咋定位，要问老狼了 哭

**Comment by AndyNull** [comment]
> > 抱歉白天没啥时间，只有晚上搞搞
> > 今天试了下，容器内存在ck，然后登录是ok的
> > 但是新ck的话，登录直接无响应
> > 控制台直接报错如下，你看看：
> > POST http://xxxxx.cn/api/cklogin 500 (Internal Server Error)
> > (anonymous) @ vendor.4eb73c88.js:15
> > (anonymous) @ vendor.4eb73c88.js:15
> > _fetch @ vendor.4eb73c88.js:15
> > o @ vendor.4eb73c88.js:15
> > async function (async)
> > o @ vendor.4eb73c88.js:15
> > create @ vendor.4eb73c88.js:15
> > Qg.t. @ vendor.4eb73c88.js:16
> > (anonymous) @ index.34a494f0.js:1
> > CKLogin @ index.34a494f0.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > dn @ vendor.4eb73c88.js:1
> > handleClick @ vendor.4eb73c88.js:1
> > Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > n @ vendor.4eb73c88.js:1
> > vendor.4eb73c88.js:15 HTTPError: Request failed with status code 500 Internal Server Error
> > at o (vendor.4eb73c88.js:15)
> > at async Promise.r. [as json] (vendor.4eb73c88.js:15)
> > at async CKLogin (index.34a494f0.js:1)
> > o @ vendor.4eb73c88.js:15
> > async function (async)
> > o @ vendor.4eb73c88.js:15
> > create @ vendor.4eb73c88.js:15
> > Qg.t. @ vendor.4eb73c88.js:16
> > (anonymous) @ index.34a494f0.js:1
> > CKLogin @ index.34a494f0.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > dn @ vendor.4eb73c88.js:1
> > handleClick @ vendor.4eb73c88.js:1
> > Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > n @ vendor.4eb73c88.js:1
> > vendor.4eb73c88.js:15 TypeError: Cannot read properties of undefined (reading 'clone')
> > at Promise.r. [as json] (vendor.4eb73c88.js:15)
> > at async CKLogin (index.34a494f0.js:1)
> > r. @ vendor.4eb73c88.js:15
> > async function (async)
> > r. @ vendor.4eb73c88.js:15
> > (anonymous) @ index.34a494f0.js:1
> > CKLogin @ index.34a494f0.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > dn @ vendor.4eb73c88.js:1
> > handleClick @ vendor.4eb73c88.js:1
> > Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > n @ vendor.4eb73c88.js:1
> > index.34a494f0.js:1 TypeError: Cannot read properties of undefined (reading 'data')
> > at CKLogin (index.34a494f0.js:1)
> > CKLogin @ index.34a494f0.js:1
> > async function (async)
> > CKLogin @ index.34a494f0.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > dn @ vendor.4eb73c88.js:1
> > handleClick @ vendor.4eb73c88.js:1
> > Vf.createBlock.onClick.t..t. @ vendor.4eb73c88.js:1
> > di @ vendor.4eb73c88.js:1
> > pi @ vendor.4eb73c88.js:1
> > n @ vendor.4eb73c88.js:1
> 
> 是最新版的吗
> 无能为力了，主要四个测试鸡都正常，没遇到这个情况不知道咋定位，要问老狼了 哭

最新版，我猜测是ip被狗东检测频繁访问短暂封禁。。因为前几天一直没用，然后重装了一下什么功能都正常，但是过一两天就又是这个情况，比较烦，，，主要是用的轻量服务器，没有办法换ip，，，

**Comment by Waikkii** [comment]
可能是接口问题，京东获取用户信息有两个api，昨天有人帮我一起定位了，backend/user.js line 429
把me-api.jd.com替换为wq.jd.com
直接改后端，不用编译，改完pm2 start试试看

**Comment by AndyNull** [comment]
> wq.jd.com
直接改域名报错更多，估计参数不对，，

我现在是直接做了随机数ip，放在header里面，表示可以

**Comment by Waikkii** [comment]
> > wq.jd.com
> > 直接改域名报错更多，估计参数不对，，
> 
> 我现在是直接做了随机数ip，放在header里面，表示可以

可以的，是个好方法。

**Comment by AndyNull** [comment]
> > > wq.jd.com
> > > 直接改域名报错更多，估计参数不对，，
> > 
> > 
> > 我现在是直接做了随机数ip，放在header里面，表示可以
> 
> 可以的，是个好方法。

应该暂时能缓解一下，主要服务器是轻量的，没法换ip。。。比较坑

**Comment by Waikkii** [comment]
> 随机数ip

随机数ip的代码可以分享一下吗

**Comment by AndyNull** [comment]
> > 随机数ip
> 
> 随机数ip的代码可以分享一下吗

function getRandIP(){
var ip = []
for(var i = 0; i<4; i++){
ip = ip+Math.floor(Math.random()*256)+"."
}
return ip
}

请求头添加：
     'CLIENT-IP': getRandIP(),
        'X-FORWARDED-FOR': getRandIP(),

**Comment by AndyNull** [comment]
> > 随机数ip
> 
> 随机数ip的代码可以分享一下吗

gg，似乎之前可以都纯属意外，，你那能不能测试一下这个的啊，我夸夸一顿操作写完代码结果无法运行，没搞过nodejs
https://wq.jd.com/user/info/GetUserAllPinInfo?_=${Date.now()}&sceneval=2&g_login_type=1&callback=userInfoCallBack&g_ty=ls',
Referer: 'https://wqs.jd.com/',

**Comment by Waikkii** [comment]
> > > 随机数ip
> > 
> > 
> > 随机数ip的代码可以分享一下吗
> 
> gg，似乎之前可以都纯属意外，，你那能不能测试一下这个的啊，我夸夸一顿操作写完代码结果无法运行，没搞过nodejs
> [https://wq.jd.com/user/info/GetUserAllPinInfo?_=${Date.now()}&sceneval=2&g_login_type=1&callback=userInfoCallBack&g_ty=ls](https://wq.jd.com/user/info/GetUserAllPinInfo?_=$%7BDate.now()%7D&sceneval=2&g_login_type=1&callback=userInfoCallBack&g_ty=ls)',
> Referer: 'https://wqs.jd.com/',

已更新，添加备用接口，实测部分半黑号me-api.jd.com返回空数据，wq.jd.com有数据。
