### ISSUE TITLE
cookie获取失败

### ISSUE THREAD

**Issue by xuexinxiansheng** [Waikkii/Waikiki_ninja#2]
昨天重装之后ninja还是可以添加ck的，但现在新老ck都不能添加，都会显示失败
还有，ninja文件夹内没有.env文件，只有.env.example文件，改了其中参数之后没用，ninja不变
大神这是新出现的bug吗，昨天还正常啊

**Comment by Waikkii** [comment]
> 昨天重装之后ninja还是可以添加ck的，但现在新老ck都不能添加，都会显示失败
> 还有，ninja文件夹内没有.env文件，只有.env.example文件，改了其中参数之后没用，ninja不变
> 大神这是新出现的bug吗，昨天还正常啊

指路原作者：https://github.com/MoonBegonia/ninja
源码在提交ck之后会进行ck有效性检测，推测可能是京东接口有概率无效。
.env.example需要改成.env
