### ISSUE TITLE
提交ck无响应

### ISSUE THREAD

**Issue by Mads0924** [Waikkii/Waikiki_ninja#21]
抓包数据显示cookie未获取到用户信息，最近频繁发生 cookie是正常可用的

**Comment by Waikkii** [comment]
能提供console的输出吗

**Comment by Waikkii** [comment]
> 抓包数据显示cookie未获取到用户信息，最近频繁发生 cookie是正常可用的

可能是接口问题，京东获取用户信息有两个api，昨天有人帮我一起定位了，backend/user.js line 429
把me-api.jd.com替换为wq.jd.com
直接改后端，不用编译，改完pm2 start试试看
