### ISSUE TITLE
请问大佬wsck是多长时间转一次，一睁眼上百条失效消息

### ISSUE THREAD

**Issue by bjl101501** [Waikkii/Waikiki_ninja#22]
请问大佬wsck是多长时间转一次，一睁眼上百条失效消息

**Comment by Waikkii** [comment]
> 请问大佬wsck是多长时间转一次，一睁眼上百条失效消息

录入转一次，后面自己脚本转吧

**Comment by bjl101501** [comment]
> > 请问大佬wsck是多长时间转一次，一睁眼上百条失效消息
> 
> 录入转一次，后面自己脚本转吧

O(∩_∩)O我以为是自动检测转呢，已经添加了转换脚本
