### ISSUE TITLE
巨佬，如何分离ninja到另一台服务器。

### ISSUE THREAD

**Issue by PoetryU** [Waikkii/Waikiki_ninja#25]
巨佬，请问这部分代码如何修改，才能实现 ninja连接部署在另外一台服务器的青龙呢?

假设 青龙host是 `http://256.256.256.256:6666`
用户名密码分别是 `username`, `password`
https://github.com/Waikkii/Waikiki_ninja/blob/main/backend/ql.js#L8-L19
```
const qlDir = process.env.QL_DIR || '/ql';
const authFile = path.join(qlDir, 'config/auth.json');

const api = got.extend({
  prefixUrl: process.env.QL_URL || 'http://localhost:5600',
  retry: { limit: 0 },
});

async function getToken() {
  const authConfig = JSON.parse(await readFile(authFile));
  return authConfig.token;
}

```

感谢巨佬

**Comment by Waikkii** [comment]
> 巨佬，请问这部分代码如何修改，才能实现 ninja连接部署在另外一台服务器的青龙呢?
> 
> 假设 青龙host是 `http://256.256.256.256:6666`
> 用户名密码分别是 `username`, `password`
> https://github.com/Waikkii/Waikiki_ninja/blob/main/backend/ql.js#L8-L19
> 
> ```
> const qlDir = process.env.QL_DIR || '/ql';
> const authFile = path.join(qlDir, 'config/auth.json');
> 
> const api = got.extend({
>   prefixUrl: process.env.QL_URL || 'http://localhost:5600',
>   retry: { limit: 0 },
> });
> 
> async function getToken() {
>   const authConfig = JSON.parse(await readFile(authFile));
>   return authConfig.token;
> }
> ```
> 
> 感谢巨佬

我没有试过容器外，但是按照原作者的方法，需要添加.env内容，QL_DIR=qinglong 容器的本地路径，QL_URL=http://localhost:5700
https://github.com/Waikkii/Waikiki_ninja#%E5%AE%B9%E5%99%A8%E5%A4%96

**Comment by PoetryU** [comment]
emmmm，不是容器外的方案，在容器外，他们还在一台机器里面。
我是想在服务器A部署ninja，服务器B部署青龙，
只设置`QL_URL`，却没有`QL_DIR`是不可以的，或者说 我如何在A访问B的`config/auth.json`



我似乎想到方案了，我把B的`config/auth.json`copy到A。感谢巨佬回复，祝学业进步

**Comment by PoetryU** [comment]
忽然发现config/auth.json 他用的不是用户名和密码，用的是token，这个是变化的，不知道如何实现同步，我可以生成一个永久外链，但是不知道这个`ql.js`该怎么改。  暂时放弃了

**Comment by Waikkii** [comment]
> 忽然发现config/auth.json 他用的不是用户名和密码，用的是token，这个是变化的，不知道如何实现同步，我可以生成一个永久外链，但是不知道这个`ql.js`该怎么改。 暂时放弃了

我记得是三天一变，你也可以写个脚本定时同步
