### ISSUE TITLE
最新的青龙无法使用

### ISSUE THREAD

**Issue by x-ddr** [Waikkii/Waikiki_ninja#29]
![image](https://user-images.githubusercontent.com/49069586/141673902-27a95e9b-0e1a-4fb8-b372-8d2a3fb8972d.png)

显示余量为零，无法添加ck

**Comment by gold2wave** [comment]
一样

**Comment by Waikkii** [comment]
没做兼容，还是用老版先

**Comment by FuckAnyProblem** [comment]
> 没做兼容，还是用老版先

旧版是哪一版啊
