### ISSUE TITLE
COOKIE登录，不能进入备注面板

### ISSUE THREAD

**Issue by mjyhj** [Waikkii/Waikiki_ninja#3]
不能进入备注面板，也不能看到推送二维码，怎么搞

**Comment by Waikkii** [comment]
我只是简单的加个dom啊。。没改前端，你想登录后进入备注的话，在frontend/src/views/login.vue的155行后加这句话：
router.push('/')
然后前端编译一下

**Comment by Waikkii** [comment]
> 不能进入备注面板，也不能看到推送二维码，怎么搞

我只是简单的加个dom啊。。没改前端，你想登录后进入备注的话，在frontend/src/views/login.vue的155行后加这句话：
router.push('/')
然后前端编译一下

**Comment by Waikkii** [comment]
> 不能进入备注面板，也不能看到推送二维码，怎么搞

编译了前端，不用dom方式了，可以进入个人中心页面了。

**Comment by mjyhj** [comment]
> > 不能进入备注面板，也不能看到推送二维码，怎么搞
> 
> 编译了前端，不用dom方式了，可以进入个人中心页面了。

更新后，在主页直接会弹出账号存在风险

**Comment by mjyhj** [comment]
> > 不能进入备注面板，也不能看到推送二维码，怎么搞
> 
> 编译了前端，不用dom方式了，可以进入个人中心页面了。

登陆后不能显示备注名，和/ql/ninja/backend/static/push.jpg推送的二维码
![1](https://user-images.githubusercontent.com/22577418/132940784-82d23193-b1e0-4a3f-92bb-4d5ff83f7e27.png)

**Comment by Waikkii** [comment]
> > > 不能进入备注面板，也不能看到推送二维码，怎么搞
> > 
> > 
> > 编译了前端，不用dom方式了，可以进入个人中心页面了。
> 
> 登陆后不能显示备注名，和/ql/ninja/backend/static/push.jpg推送的二维码
> ![1](https://user-images.githubusercontent.com/22577418/132940784-82d23193-b1e0-4a3f-92bb-4d5ff83f7e27.png)

慢慢来吧，刚学了vue，功能过几天加上去

**Comment by Waikkii** [comment]
> > > 不能进入备注面板，也不能看到推送二维码，怎么搞
> > 
> > 
> > 编译了前端，不用dom方式了，可以进入个人中心页面了。
> 
> 登陆后不能显示备注名，和/ql/ninja/backend/static/push.jpg推送的二维码
> ![1](https://user-images.githubusercontent.com/22577418/132940784-82d23193-b1e0-4a3f-92bb-4d5ff83f7e27.png)

备注功能写好了，push老狼应该是自己也没写，过几天写写看

**Comment by Waikkii** [comment]
> 不能进入备注面板，也不能看到推送二维码，怎么搞

二维码参考这个
```html
<div class="card">
  <div class="card-header">
    <div class="flex items-center justify-between">
      <p class="card-title">二维码</p>
    </div>
  </div>
  <div class="card-body text-center">
    <img src="@/assets/qrcode.png" :width="256" class="m-auto" />
  </div>
  <div class="card-footer"></div>
</div>
```
图片放在frontend/assets
