### ISSUE TITLE
今天下午安装的ninja，5701端口只有这些

### ISSUE THREAD

**Issue by xuexinxiansheng** [Waikkii/Waikiki_ninja#4]
![image](https://user-images.githubusercontent.com/63955913/132945663-f29dc2ca-f12e-4c11-bbf7-9a58c8d5863b.png)

**Comment by wk333** [comment]
一样，好像有错
![图片](https://user-images.githubusercontent.com/30464860/132945712-66ab1753-6af0-4e13-a197-cbea3474fc2c.png)

**Comment by Waikkii** [comment]
> ![image](https://user-images.githubusercontent.com/63955913/132945663-f29dc2ca-f12e-4c11-bbf7-9a58c8d5863b.png)
> 
> 

修改env文件里的变量，默认都不显示

**Comment by wk333** [comment]
尴尬了，突然发现没有.env这个文件
执行
cp .env.example .env
就好了
