### ISSUE TITLE
ninja界面，还是不行，5701界面还是不变，也pm2 start重启了

### ISSUE THREAD

**Issue by xuexinxiansheng** [Waikkii/Waikiki_ninja#5]
![image](https://user-images.githubusercontent.com/63955913/132947016-92fdbdaa-324d-44b3-aa09-5c7f230ded8a.png)

**Comment by xuexinxiansheng** [comment]
以前默认打开不是挺好的吗，为啥要改了

**Comment by mjyhj** [comment]
先重启一次ninja，删掉浏览器缓存或者ctrl+F5刷新
