### ISSUE TITLE
第二个容器，ninja文件夹没有内容，执行所有命令之后，都没有数据

### ISSUE THREAD

**Issue by xuexinxiansheng** [Waikkii/Waikiki_ninja#7]
![image](https://user-images.githubusercontent.com/63955913/132972269-891fef15-dcf2-4322-8e1a-c5324445818d.png)

**Comment by Waikkii** [comment]
你咋映射的。。。

**Comment by xuexinxiansheng** [comment]
> 你咋映射的。。。

![image](https://user-images.githubusercontent.com/63955913/132979788-6f79b655-100b-411c-8917-f9abdfb14423.png)
我是这样做的

**Comment by Waikkii** [comment]
> > 你咋映射的。。。
> 
> ![image](https://user-images.githubusercontent.com/63955913/132979788-6f79b655-100b-411c-8917-f9abdfb14423.png)
> 我是这样做的

git clone操作是在容器内的，所以步骤2里的目录应该是ql而不是ql1吧，你可以看看你容器内是不是有ql1/ninja。

**Comment by xuexinxiansheng** [comment]
> > > 你咋映射的。。。
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/63955913/132979788-6f79b655-100b-411c-8917-f9abdfb14423.png)
> > 我是损坏的
> 
> git clone操作是在容器内的，所以步骤2里的目录应该是ql而不是ql1吧，你可以看看你的容器内是不是有ql1/ninja。

对，就是这个问题，我进入容器之后，显示的总是:/ql，而不是第二个容器的ql1文件
![image](https://user-images.githubusercontent.com/63955913/132980180-8e87dcbe-b7cf-49fb-bd8d-5cae431a1321.png)

**Comment by Waikkii** [comment]
> > > > 你咋映射的。。。
> > > 
> > > 
> > > ![图片](https://user-images.githubusercontent.com/63955913/132979788-6f79b655-100b-411c-8917-f9abdfb14423.png)
> > > 我是损坏的
> > 
> > 
> > git clone操作是在容器内的，所以步骤2里的目录应该是ql而不是ql1吧，你可以看看你的容器内是不是有ql1/ninja。
> 
> 对，就是这个问题，我进入容器之后，显示的总是:/ql，而不是第二个容器的ql1文件
> ![image](https://user-images.githubusercontent.com/63955913/132980180-8e87dcbe-b7cf-49fb-bd8d-5cae431a1321.png)

容器内都是ql，多容器只是映射的目录不一样，进容器2后操作和容器1一样.

**Comment by xuexinxiansheng** [comment]
> > > > > 你咋映射的。。。
> > > > 
> > > > 
> > > > ![图片](https://user-images.githubusercontent.com/63955913/132979788-6f79b655-100b-411c-8917-f9abdfb14423.png)
> > > > 我是损坏的
> > > 
> > > 
> > > git clone操作是在容器内的，所以步骤2里的目录应该是ql而不是ql1吧，你可以看看你的容器内是不是有ql1/ninja。
> > 
> > 
> > 对，就是这个问题，我进入容器之后，显示的总是：/ql，而不是第二个容器的ql1文件
> > ![图片](https://user-images.githubusercontent.com/63955913/132980180-8e87dcbe-b7cf-49fb-bd8d-5cae431a1321.png)
> 
> 容器内都是ql，多容器只是一个映射的目录不一样，进容器2后操作和容器1。

那怎么会出现第二个容器ninja文件夹为空的情况呢？，而且我去更改第一个容器的env，只是第一个ninja界面会改变，那第二个ninja要怎么改呢
