### ISSUE TITLE
建议更新一下我最新的ninja修改版代码

### ISSUE THREAD

**Issue by huiyi9420** [Waikkii/Waikiki_ninja#9]
最新版支持对wskey的有效性检查
目前提交的代码就是所有修改的有效代码，多余部分以及我们俩仓库通用部分我已经移除了代码

**Comment by Waikkii** [comment]
> 最新版支持对wskey的有效性检查
> 目前提交的代码就是所有修改的有效代码，多余部分以及我们俩仓库通用部分我已经移除了代码

牛哇牛哇！！！我去学习一下
